@startuml
[-> Validator : Validate(number)
activate Validator
Validator -> RomanNumber : << create >>
activate RomanNumber
loop
	Validator -> RomanNumber : Append(digit)
	opt digit is not allowed
		Validator <-- RomanNumber : throw invalid_argument
		[<-- Validator : false
	end
end
deactivate RomanNumber
destroy RomanNumber
[<-- Validator : true
deactivate Validator
@enduml